name: Validate dotnet

on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches: ["main"]
    
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

  schedule:
    - cron: '0 1 * * *'

env:
  GDN_BINSKIM_TARGET: "./src/Whetstone.SecurityCamera.Service/bin/Release/net7.0/*.dll"
  AZURE_VISIONSUBSCRIPTIONKEY: ${{ secrets.AZURE_VISIONSUBSCRIPTIONKEY }}
  AZURE_VISIONENDPOINT: ${{ secrets.AZURE_VISIONENDPOINT }}

jobs:
  setup-version:
    runs-on: 'windows-latest'
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:

      - name: List Environment Variables
        run: env

      - name: Checkout
        uses: actions/checkout@v3


      - name: setup-dotnet
        uses: xt0rted/setup-dotnet@v1.5.0
        with:
          dotnet-version: '7.0'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          queries: security-and-quality

      - name: Build with dotnet
        run: dotnet build ./src --configuration Release
    
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
        
      - name: Test
        run: dotnet test ./src --no-build --verbosity normal --configuration Release

      # Run analyzers
      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@preview
        id: msdo
        
      # Upload alerts to the Security tab
      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}      
